### ISSUE TITLE
How to import algs from a PDF sheet.

### ISSUE THREAD

**Issue by abunickabhi** [jonatanklosko/alg-sets#1]
Hey,

Do I have to use MongoDB to import algs and store them?
(Right now I have to add them one by one)

I do have some BLD algs stored in excel sheet and exported them as pdf here: [https://github.com/abunickabhi/5style/blob/master/5-style-edge.pdf](url)

**Comment by jonatanklosko** [comment]
Hey there, on the alg set page next to the `+` icon, there is an export/import icon that allows you to bulk-edit the algs, so you can just paste a list of algs there, each in a single line.
